-- ============================================================
-- PART 5 — Gucci
-- Step 1: Insert brand row
-- Step 2: Insert 50 products across categories
-- Run in Neon Query Editor (each INSERT separately if needed)
-- ============================================================

-- STEP 1: INSERT GUCCI BRAND
INSERT INTO brands (brand_name, slug, country_of_origin, description, website_url, is_featured, created_at, updated_at)
VALUES (
    'Gucci',
    'gucci',
    'Italy',
    'Founded in Florence in 1921, Gucci is one of the world''s leading luxury fashion brands, known for its Italian craftsmanship and bold, eclectic aesthetic.',
    'https://www.gucci.com',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- STEP 2: INSERT GUCCI PRODUCTS
-- ============================================================

-- DRESSES & EVENING GOWNS (8 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Jacquard Silk Midi Dress','Gucci','WOMEN','GG Jacquard Silk','Gucci SS 2026','Bias-cut midi dress in signature GG jacquard silk with a V-neckline and fluted hem.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Floral Embroidered Tulle Gown','Gucci','WOMEN','Silk Tulle','Gucci SS 2026','Floor-length silk tulle gown with hand-applied floral embroidery and a corseted bodice.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Horsebit Satin Evening Gown','Gucci','WOMEN','Stretch Satin','Gucci FW 2026','Sleek stretch satin column gown featuring a sculptural Horsebit chain embellishment at the waist.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Velvet A-Line Mini Dress','Gucci','WOMEN','Crushed Velvet','Gucci FW 2026','Deep jewel-tone crushed velvet mini dress with a square neckline and puff sleeves.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Printed Crepe Wrap Dress','Gucci','WOMEN','Silk Crepe','Gucci SS 2026','Wrap-style crepe dress in a bold Gucci floral print with a self-tie waist.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Sequined Broderie Mini Dress','Gucci','WOMEN','Sequined Broderie','Gucci FW 2026','All-over sequin-embellished mini dress with broderie anglaise trim and a babydoll silhouette.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Canvas Monogram Shirtdress','Gucci','WOMEN','GG Supreme Canvas','Gucci SS 2026','Oversized shirtdress crafted in the iconic GG Supreme canvas with contrast leather trims.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Interlocking G Knit Dress','Gucci','WOMEN','Fine Wool Knit','Gucci FW 2026','Form-fitting ribbed knit dress with an interlocking G logo jacquard pattern at the hem.','ACTIVE',NULL,NOW(),NOW());

-- TOPS & SILK BLOUSES (6 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Monogram Silk Blouse','Gucci','WOMEN','GG Print Silk','Gucci SS 2026','Relaxed silk blouse in the iconic GG monogram print with a point collar and ruffle cuffs.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Horsebit-Trim Silk Cami','Gucci','WOMEN','Silk Charmeuse','Gucci SS 2026','Bias-cut silk charmeuse cami with a signature Horsebit chain detail at the neckline.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web-Stripe Cotton Polo','Gucci','UNISEX','Pique Cotton','Gucci SS 2026','Classic pique cotton polo shirt with the signature green-red-green Web stripe on the collar.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Embroidered Logo Poplin Shirt','Gucci','WOMEN','Cotton Poplin','Gucci SS 2026','Crisp white cotton poplin shirt with a tonal Gucci script embroidery on the chest pocket.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Tiger Embroidery Silk Top','Gucci','WOMEN','Silk Twill','Gucci FW 2026','Silk twill blouse featuring the Gucci tiger embroidery motif — a House signature.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Interlocking G Cotton Tee','Gucci','UNISEX','Supima Cotton','Gucci SS 2026','Clean-cut Supima cotton T-shirt with a tone-on-tone Interlocking G logo print.','ACTIVE',NULL,NOW(),NOW());

-- OUTERWEAR & TAILORED JACKETS (5 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Canvas Blouson Jacket','Gucci','UNISEX','GG Supreme Canvas','Gucci FW 2026','Zip-front blouson jacket in the GG Supreme canvas with leather collar and Gucci Web lining.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Double-Breasted Wool Coat','Gucci','WOMEN','Virgin Wool','Gucci FW 2026','Structured double-breasted longline coat in pressed virgin wool with gold Horsebit buttons.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web-Stripe Bomber Jacket','Gucci','UNISEX','Nylon Taffeta','Gucci SS 2026','Lightweight nylon taffeta bomber with the signature Web stripe across the chest and cuffs.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Horsebit Boucle Blazer','Gucci','WOMEN','Boucle Tweed','Gucci FW 2026','Collarless boucle blazer with fringe trim and polished Horsebit hardware buttons.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Leather Biker Jacket with GG Lining','Gucci','UNISEX','Smooth Calfskin','Gucci FW 2026','Asymmetric zip calfskin biker jacket with a signature GG print interior lining.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- BOTTOMS, SHORTS & CULOTTES (4 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Bottoms, Shorts & Culottes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Monogram Wide-Leg Trousers','Gucci','WOMEN','GG Jacquard','Gucci FW 2026','Wide-leg trousers in a GG jacquard fabric with a high waist and elasticated back.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Bottoms, Shorts & Culottes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web-Stripe Cotton Shorts','Gucci','MEN','Cotton Drill','Gucci SS 2026','Tailored cotton drill shorts with a signature Web stripe down the side seam.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Bottoms, Shorts & Culottes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Silk Pyjama Trousers','Gucci','WOMEN','GG Print Silk','Gucci SS 2026','Relaxed silk pyjama-style trousers in a signature GG print with a drawstring waist.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Bottoms, Shorts & Culottes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Tailored Wool Dress Trousers','Gucci','MEN','Italian Wool','Gucci FW 2026','Classic flat-front dress trousers in a fine Italian wool blend with a tapered leg.','ACTIVE',NULL,NOW(),NOW());

-- LUXURY LEATHER BAGS (10 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Dionysus Mini Shoulder Bag','Gucci','WOMEN','GG Supreme Canvas','Gucci SS 2026','Iconic mini shoulder bag in GG Supreme canvas with a Dionysus tiger-head closure.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Ophidia GG Tote Bag','Gucci','WOMEN','GG Supreme Canvas','Gucci SS 2026','Spacious open-top tote in GG Supreme canvas with the Double G hardware and Web strap trim.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Marmont Small Crossbody Bag','Gucci','WOMEN','Matelasse Leather','Gucci SS 2026','Chevron-quilted matelasse leather crossbody with a Double G gold-tone hardware clasp.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Bamboo Handle Top Bag','Gucci','WOMEN','Smooth Calfskin','Gucci SS 2026','Structured top-handle bag in smooth calfskin with Gucci''s iconic bamboo handle hardware.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Horsebit Chain Medium Shoulder Bag','Gucci','WOMEN','Smooth Calfskin','Gucci FW 2026','Medium shoulder bag in smooth calfskin with the signature Horsebit chain strap.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Supreme Backpack','Gucci','UNISEX','GG Supreme Canvas','Gucci FW 2026','Classic GG Supreme canvas backpack with leather trims, front pockets, and a padded back.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Interlocking G Leather Belt Bag','Gucci','UNISEX','Smooth Calfskin','Gucci SS 2026','Compact calfskin belt bag with the Interlocking G buckle and a detachable chain strap.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Ophidia Mini Bucket Bag','Gucci','WOMEN','GG Supreme Canvas','Gucci SS 2026','Petite drawstring bucket bag in GG Supreme canvas with an adjustable leather shoulder strap.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Gucci Logo Duffle Bag','Gucci','UNISEX','GG Supreme Canvas','Gucci FW 2026','Weekend duffle in GG Supreme canvas with leather handles and a detachable shoulder strap.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Sylvie Web Chain Mini Bag','Gucci','WOMEN','Smooth Calfskin','Gucci FW 2026','Structured mini bag with the iconic Web strap detail and a gold-tone chain handle.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- FOOTWEAR & LEATHER SHOES (8 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Horsebit Loafers','Gucci','UNISEX','Smooth Calfskin','Gucci SS 2026','The iconic Gucci Horsebit loafer in polished calfskin — a timeless House signature since 1953.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Princetown Leather Mules','Gucci','WOMEN','Smooth Calfskin','Gucci SS 2026','Backless Princetown mules in smooth calfskin with the signature Horsebit hardware.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Canvas Sneakers','Gucci','UNISEX','GG Supreme Canvas','Gucci SS 2026','Court-style sneakers in GG Supreme canvas with leather trims and a Web stripe at the heel.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Floral Embroidered Pumps','Gucci','WOMEN','Embroidered Satin','Gucci FW 2026','Pointed-toe pumps in satin with hand-embroidered floral motifs and a slender block heel.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web Stripe Sandals','Gucci','WOMEN','Nappa Leather','Gucci SS 2026','Flat leather sandals with a toe-post and the iconic Web stripe across the vamp.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Chelsea Ankle Boots','Gucci','UNISEX','Polished Calfskin','Gucci FW 2026','Sleek Chelsea ankle boots in polished calfskin with elastic side gussets and a stacked heel.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Screener Leather High-Top Sneakers','Gucci','UNISEX','Smooth Leather','Gucci FW 2026','High-top leather sneakers with a chunky cupsole and the Double G logo at the tongue.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Platform Espadrilles','Gucci','WOMEN','GG Canvas & Jute','Gucci SS 2026','Wedge espadrilles in GG canvas with a jute platform and leather ankle-tie straps.','ACTIVE',NULL,NOW(),NOW());

-- MONOGRAM SILK ACCESSORIES (5 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Silk Twill Scarf 90x90','Gucci','UNISEX','Silk Twill','Gucci SS 2026','90x90cm silk twill scarf in a signature GG monogram print with hand-rolled edges.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Interlocking G Leather Belt','Gucci','UNISEX','Smooth Calfskin','Gucci SS 2026','Classic 3.5cm calfskin leather belt with the polished Interlocking G buckle.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web Stripe Wool Scarf','Gucci','UNISEX','Merino Wool','Gucci FW 2026','Merino wool scarf featuring the signature Gucci Web stripe woven across each end.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Marmont Card Case','Gucci','UNISEX','Matelasse Leather','Gucci SS 2026','Compact quilted matelasse leather card case with the Double G logo hardware closure.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Tiger Head Baseball Cap','Gucci','UNISEX','Cotton Twill','Gucci SS 2026','Six-panel cotton twill baseball cap with an embroidered Gucci tiger head on the front.','ACTIVE','NEW_ARRIVAL',NOW(),NOW());

-- MEN'S DESIGNER COLLECTION (4 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Embossed Leather Loafer Men','Gucci','MEN','GG Embossed Leather','Gucci FW 2026','Men''s penny loafers in GG-embossed leather with a leather sole and stacked heel.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Web-Stripe Technical Track Jacket','Gucci','MEN','Technical Jersey','Gucci SS 2026','Zip-front technical jersey track jacket with the iconic Web stripe across the chest.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci GG Canvas Baseball Cap','Gucci','MEN','GG Supreme Canvas','Gucci SS 2026','Unstructured baseball cap in GG Supreme canvas with a curved brim and metal logo badge.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'gucci' LIMIT 1),'PHYSICAL_APPAREL','Gucci Interlocking G Oxford Shirt','Gucci','MEN','Cotton Oxford','Gucci SS 2026','Classic Oxford cloth shirt with tonal Interlocking G embroidery on the chest pocket.','ACTIVE',NULL,NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'Gucci';
