-- ============================================================
-- PART 2 of 4 — Vattanac Brewery
-- 31 products: Craft Beers (16) + Packaged Foods (15)
-- Run in Neon Query Editor
-- Prerequisite: brands row with slug='vattanac' exists
-- ============================================================

-- CRAFT BEERS & COLD BEVERAGES (16 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Gold Reserve Lager 330ml','Vattanac Brewery','UNISEX','Core Range','Award-winning golden lager brewed from 100% barley malt with floral hop notes.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Dark Stout 330ml','Vattanac Brewery','UNISEX','Core Range','Rich roasted malt stout with notes of dark chocolate, espresso, and caramel.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Wheat Beer 500ml','Vattanac Brewery','UNISEX','Core Range','Hazy Belgian-style wheat beer brewed with coriander and orange peel for a citrus finish.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac IPA 330ml','Vattanac Brewery','UNISEX','Seasonal Brews','Double dry-hopped India Pale Ale with tropical fruit aromas and a bitter finish.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Ginger Beer 330ml','Vattanac Brewery','UNISEX','Core Range','Naturally brewed non-alcoholic ginger beer with a spicy kick and smooth sweetness.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Premium Lager 6-Pack','Vattanac Brewery','UNISEX','Core Range','Six-pack cluster of Vattanac Premium Craft Lager 330ml cans — retail ready.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Lager Master Carton 24x','Vattanac Brewery','UNISEX','Core Range','Trade master carton of 24x330ml Vattanac Premium Lager cans for retail wholesale.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Mango Craft Soda 330ml','Vattanac Brewery','UNISEX','Seasonal Brews','Non-alcoholic sparkling mango craft soda made with real Kampot mango juice.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Lime Sparkling Water 500ml','Vattanac Brewery','UNISEX','Core Range','Naturally carbonated mineral water infused with Cambodian kaffir lime zest.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Red Ale 330ml','Vattanac Brewery','UNISEX','Seasonal Brews','Irish-style red ale with a deep copper colour, toffee malt sweetness, and a dry finish.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Passion Fruit Sour 330ml','Vattanac Brewery','UNISEX','Seasonal Brews','Berlin-style sour ale fermented with passion fruit purée — refreshingly tart.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Blonde Ale 330ml','Vattanac Brewery','UNISEX','Core Range','Easy-drinking blonde ale with soft maltiness and a lightly floral hop character.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Jasmine Rice Lager 330ml','Vattanac Brewery','UNISEX','Heritage Edition','Unique Cambodia-inspired lager brewed with locally grown jasmine rice for a clean finish.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Coconut Porter 330ml','Vattanac Brewery','UNISEX','Heritage Edition','Tropical porter brewed with toasted Cambodian coconut flakes for a rich sweet finish.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Mixed Tasting Pack 4x330ml','Vattanac Brewery','UNISEX','Core Range','Mixed four-can tasting pack: Lager, Stout, IPA, and Blonde Ale varieties.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Kampot Pepper Spiced Lager 330ml','Vattanac Brewery','UNISEX','Heritage Edition','Limited heritage lager spiced with certified Kampot pepper for a unique peppery warmth.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Craft Beers & Cold Beverages' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Zero-Alcohol Lager 330ml','Vattanac Brewery','UNISEX','Core Range','Full-flavour zero-alcohol Cambodian lager — all the taste with none of the alcohol.','ACTIVE','NEW_ARRIVAL',NOW(),NOW());

-- PACKAGED FOODS & SNACKS (15 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Kampot Pepper Cashews 150g','Vattanac Brewery','UNISEX','Gourmet Pantry','Premium roasted cashews tossed in authentic Kampot pepper, sea salt, and lime zest.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Dried Mango Slices 100g','Vattanac Brewery','UNISEX','Gourmet Pantry','Sun-dried Cambodian mango slices with no added sugar — naturally sweet and chewy.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Rice Crackers with Sesame 120g','Vattanac Brewery','UNISEX','Gourmet Pantry','Traditional Cambodian rice crackers topped with toasted sesame seeds and a light soy glaze.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Artisan Dark Chocolate Bar 80g','Vattanac Brewery','UNISEX','Gourmet Pantry','72% Mondulkiri cacao dark chocolate bar with single-origin notes of fruit and earth.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Premium Ratanakiri Coffee 250g','Vattanac Brewery','UNISEX','Gourmet Pantry','Specialty grade blended ground coffee from Ratanakiri highlands — medium roast.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Coconut Palm Sugar 300g','Vattanac Brewery','UNISEX','Gourmet Pantry','Unrefined organic coconut palm sugar from Kampong Speu — low glycaemic natural sweetener.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Lemongrass Herb Tea 20 Bags','Vattanac Brewery','UNISEX','Gourmet Pantry','Fragrant dried lemongrass and pandan leaf herbal tea — caffeine-free and soothing.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Kampot Pepper Hot Sauce 150ml','Vattanac Brewery','UNISEX','Gourmet Pantry','Artisan hot sauce made from certified black Kampot peppercorns in a vinegar base.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Tamarind Candy Pack 200g','Vattanac Brewery','UNISEX','Gourmet Pantry','Classic Cambodian sweet-sour tamarind candy made with natural tamarind and cane sugar.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Mixed Premium Nuts Bag 200g','Vattanac Brewery','UNISEX','Gourmet Pantry','Mixed premium nuts: macadamia, almonds, cashews, and walnuts — dry-roasted and lightly salted.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Jackfruit Chips 80g','Vattanac Brewery','UNISEX','Gourmet Pantry','Crispy baked jackfruit chips with a light dusting of Kampot pepper and sea salt.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Premium Jasmine Rice 1kg','Vattanac Brewery','UNISEX','Gourmet Pantry','Award-winning Cambodian fragrant jasmine rice — long-grain and naturally aromatic.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Mondulkiri Wildflower Honey 250g','Vattanac Brewery','UNISEX','Gourmet Pantry','Raw unfiltered wildflower honey harvested from the forests of Mondulkiri province.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Bamboo Salt Seasoning 100g','Vattanac Brewery','UNISEX','Gourmet Pantry','Korean-inspired bamboo salt roasted nine times for a deep umami mineral flavour.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Artisan Granola 350g','Vattanac Brewery','UNISEX','Gourmet Pantry','Handcrafted granola with toasted oats, Cambodian coconut flakes, pumpkin seeds, and local honey.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Packaged Foods & Snacks' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'vattanac' LIMIT 1),'PHYSICAL_FMCG','Vattanac Gourmet Pantry Gift Box','Vattanac Brewery','UNISEX','Gourmet Pantry','Premium curated gift box: Cashews + Dark Chocolate + Coffee + Honey + Kampot Pepper Sauce.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'Vattanac Brewery';
