-- ============================================================
-- PART 3 of 4 — Kesararam Health & Beauty
-- 37 products: Skincare & Cosmetics (22) + Pharmacy & Wellness (15)
-- Run in Neon Query Editor
-- Prerequisite: brands row with slug='kesararam-wellness' exists
-- ============================================================

-- SKINCARE & COSMETICS (22 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Golden Silk Moisturiser 50ml','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Intensive moisturising cream with golden silk sericin, hyaluronic acid, and vitamin E.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Vitamin C Brightening Serum 30ml','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','15% vitamin C serum with niacinamide and ferulic acid for a radiant, even skin tone.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Retinol Night Cream 30ml','Kesararam Health & Beauty','WOMEN','Night Ritual','Encapsulated retinol night cream with ceramides and peptides for overnight skin renewal.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Micellar Cleansing Water 200ml','Kesararam Health & Beauty','UNISEX','Core Skincare','Gentle micellar water that removes makeup and impurities without stripping moisture.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Hydrating Sheet Mask 5-Pack','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Pack of 5 silk-fiber sheet masks soaked in a hyaluronic acid and aloe vera essence.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam SPF 50 Sunscreen Fluid 50ml','Kesararam Health & Beauty','UNISEX','Core Skincare','Lightweight broad-spectrum SPF 50 PA++++ sunscreen fluid with blue-light protection.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Eye Contour Cream 15ml','Kesararam Health & Beauty','WOMEN','Night Ritual','De-puffing eye contour cream with caffeine and collagen peptides for the periorbital area.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Rose Hip Facial Oil 30ml','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Cold-pressed rose hip seed oil rich in omega fatty acids for skin repair and glow.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Exfoliating Enzyme Mask 75ml','Kesararam Health & Beauty','WOMEN','Core Skincare','Papaya and pineapple enzyme mask that gently exfoliates and brightens dull skin.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Hydra-Plump Toner 150ml','Kesararam Health & Beauty','WOMEN','Core Skincare','Alcohol-free essence toner with 5 types of hyaluronic acid for deep plumping hydration.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Matte Lipstick Terracotta Rose','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Long-lasting matte lipstick in a flattering terracotta rose shade with vitamin E conditioning.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Cushion Foundation SPF 40','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Buildable coverage cushion foundation with SPF 40 and a natural satin finish.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Waterproof Brow Pomade','Kesararam Health & Beauty','WOMEN','Core Skincare','Waterproof brow pomade in a micro-precision pot for defined, feathered brows.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Illuminating Primer 30ml','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Rose-gold illuminating primer that blurs pores and adds a lit-from-within radiance.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam 16-Hour Setting Spray 100ml','Kesararam Health & Beauty','WOMEN','Core Skincare','Micro-fine setting mist that locks makeup for up to 16 hours with a dewy finish.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Vitamin C Lip Treatment','Kesararam Health & Beauty','WOMEN','Core Skincare','Overnight vitamin C and shea butter lip treatment for soft, plumped lips by morning.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Lash Growth Serum 5ml','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Clinically tested lash growth serum with biotin and keratin peptides for fuller lashes.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Peppermint Scalp Serum 50ml','Kesararam Health & Beauty','UNISEX','Wellness Range','Invigorating scalp serum with peppermint oil and zinc PCA to balance scalp health.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Triple Butter Body Butter 200ml','Kesararam Health & Beauty','WOMEN','Wellness Range','Rich body butter with shea, mango and cocoa butter for deep 24-hour skin nourishment.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Glycolic Acid Toner 150ml','Kesararam Health & Beauty','WOMEN','Core Skincare','8% glycolic acid exfoliating toner for smooth texture, refined pores, and even tone.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Clay Purifying Mask 75ml','Kesararam Health & Beauty','UNISEX','Core Skincare','Kaolin and bentonite clay mask with green tea extract for deep pore cleansing.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Skincare & Cosmetics' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Complete Skincare Gift Set','Kesararam Health & Beauty','WOMEN','Glow Collection 2026','Luxury gift set: Silk Serum 30ml + Moisturiser 30ml + Eye Cream 10ml in a silk pouch.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- PHARMACY & WELLNESS (15 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Multivitamin Daily Complex 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Complete A-Z multivitamin with 26 essential nutrients for daily energy and immunity.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Omega-3 Fish Oil 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','High-strength omega-3 fatty acid supplement for heart, brain, and joint health.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Marine Collagen Peptides 200g','Kesararam Health & Beauty','WOMEN','Wellness Range','Hydrolyzed marine collagen peptides powder for skin elasticity and joint support.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam 10-Strain Probiotics 30 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','10-strain probiotic capsules with 50 billion CFU for gut and immune health.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Vitamin D3 + K2 90 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Combined D3 and K2 supplement for optimal calcium absorption and bone density.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Magnesium Glycinate 90 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Highly bioavailable magnesium glycinate for muscle recovery and improved sleep quality.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Turmeric & Ginger 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Curcumin-rich turmeric with black pepper extract and ginger for inflammation support.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Hair Biotin Complex 60 Caps','Kesararam Health & Beauty','WOMEN','Wellness Range','Biotin, zinc, selenium, and saw palmetto for healthy hair growth and thickness.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Melatonin 5mg 60 Tabs','Kesararam Health & Beauty','UNISEX','Wellness Range','Fast-dissolve melatonin tablets to support healthy sleep onset and circadian rhythm.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Ashwagandha KSM-66 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Clinically dosed KSM-66 ashwagandha root extract for stress reduction and cortisol balance.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Electrolyte Hydration Sachets 14-Pack','Kesararam Health & Beauty','UNISEX','Wellness Range','Zero-sugar electrolyte sachets with sodium, potassium, and magnesium for rapid hydration.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Zinc & Vitamin C Immunity 90 Tabs','Kesararam Health & Beauty','UNISEX','Wellness Range','Effervescent zinc and vitamin C tablets for immune system fortification.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Detox Green Tea Capsules 30 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','EGCG-rich green tea extract capsules for antioxidant protection and gentle detox support.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Iron + Folate Complex 60 Caps','Kesararam Health & Beauty','WOMEN','Wellness Range','Gentle non-constipating iron bisglycinate with folate for women''s daily iron needs.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Wellness Starter Bundle','Kesararam Health & Beauty','UNISEX','Wellness Range','Starter kit: Multivitamin + Omega-3 + Probiotic + Vitamin D3 in gift packaging.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Coenzyme Q10 200mg 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','200mg CoQ10 softgels in an oil suspension for maximum bioavailability and antioxidant support.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Pharmacy & Wellness' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kesararam-wellness' LIMIT 1),'PHYSICAL_FMCG','Kesararam Vitamin B Complex 60 Caps','Kesararam Health & Beauty','UNISEX','Wellness Range','Full B-spectrum: B1, B2, B3, B5, B6, B7, B9, B12 for energy and nervous system support.','ACTIVE',NULL,NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'Kesararam Health & Beauty';
