-- ============================================================
-- PART 6 — Louis Vuitton
-- Step 1: Insert brand row
-- Step 2: Insert 50 products across categories
-- Run in Neon Query Editor (each INSERT separately if needed)
-- ============================================================

-- STEP 1: INSERT LOUIS VUITTON BRAND
INSERT INTO brands (brand_name, slug, country_of_origin, description, website_url, is_featured, created_at, updated_at)
VALUES (
    'Louis Vuitton',
    'louis-vuitton',
    'France',
    'Founded in Paris in 1854, Louis Vuitton is the world''s most valuable luxury brand, renowned for its Monogram canvas, leather goods, and ready-to-wear collections.',
    'https://www.louisvuitton.com',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- STEP 2: INSERT LOUIS VUITTON PRODUCTS
-- ============================================================

-- LUXURY LEATHER BAGS (14 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Neverfull MM Tote','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','The iconic Neverfull MM in Monogram canvas with supple leather trims and removable pouch.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Speedy 30 Bandouliere','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','The Speedy 30 with a detachable shoulder strap in classic Monogram canvas and tan leather trim.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Pochette Metis','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','Elegant flap-closure crossbody in Monogram canvas with a D-ring and S-lock hardware.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Alma BB','Louis Vuitton','WOMEN','Epi Leather','LV SS 2026','Compact structured Alma BB in textured Epi leather with polished brass LV padlock.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Capucines MM','Louis Vuitton','WOMEN','Taurillon Leather','LV FW 2026','The Capucines MM in supple taurillon leather with an LV clasp and a top-handle design.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton OnTheGo GM Tote','Louis Vuitton','WOMEN','Monogram Empreinte','LV SS 2026','Oversized reversible tote in embossed Monogram Empreinte leather — roomy and refined.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Twist MM Shoulder Bag','Louis Vuitton','WOMEN','Epi Leather','LV FW 2026','The Twist MM in smooth Epi leather with the LV-shaped twist closure and a chain strap.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Palm Springs Mini Backpack','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','Mini Palm Springs backpack in Monogram canvas with two front pockets and leather trims.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Keepall 50 Bandouliere','Louis Vuitton','UNISEX','Damier Ebene Canvas','LV FW 2026','The iconic Keepall 50 weekend bag in Damier Ebene canvas with a detachable strap.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Multi Pochette Accessories','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','Three-in-one pochette set: mini crescent bag, coin purse, and pochette on one strap.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Dauphine MM','Louis Vuitton','WOMEN','Monogram Reverse Canvas','LV FW 2026','The Dauphine MM in Monogram Reverse canvas with LV circle closure and a chain-leather strap.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton District PM Crossbody','Louis Vuitton','MEN','Damier Graphite Canvas','LV FW 2026','Men''s slim messenger bag in Damier Graphite canvas with a removable shoulder strap.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Lockit MM','Louis Vuitton','WOMEN','Taurillon Leather','LV SS 2026','Clean structured Lockit tote in supple Taurillon with the padlock-inspired LV clasp.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Luxury Leather Bags' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton New Wave Chain Bag MM','Louis Vuitton','WOMEN','Quilted Calfskin','LV SS 2026','Soft quilted calfskin bag with a wavy stitch pattern and a double-chain shoulder strap.','ACTIVE',NULL,NOW(),NOW());

-- DRESSES & EVENING GOWNS (7 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Denim Dress','Louis Vuitton','WOMEN','LV Monogram Denim','LV SS 2026','A-line mini dress crafted from LV-logo denim with contrast stitching and front pockets.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Crepe Pleated Evening Dress','Louis Vuitton','WOMEN','Silk Crepe','LV FW 2026','Floor-length pleated silk crepe gown in the signature LV damier check print on a nude base.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Broderie Anglaise Dress','Louis Vuitton','WOMEN','Broderie Anglaise','LV SS 2026','Short broderie anglaise dress with puff sleeves and a tiered frill hem.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Knit Dress','Louis Vuitton','WOMEN','Monogram Knit','LV FW 2026','Form-fitting ribbed knit dress with an all-over monogram intarsia pattern and long sleeves.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Fluid Silk Wrap Dress','Louis Vuitton','WOMEN','Silk Charmeuse','LV SS 2026','Bias-cut silk charmeuse wrap dress with a V-neckline and the LV floral monogram print.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Crochet Midi Dress','Louis Vuitton','WOMEN','Crochet Cotton','LV SS 2026','Handcrafted open crochet midi dress with a slip lining and a self-tie belt.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Dresses & Evening Gowns' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Embossed Velvet Gown','Louis Vuitton','WOMEN','LV-Embossed Velvet','LV FW 2026','Floor-length velvet gown with an all-over embossed LV monogram and a draped off-shoulder neckline.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- TOPS & SILK BLOUSES (5 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Silk Blouse','Louis Vuitton','WOMEN','Monogram Silk','LV SS 2026','Fluid silk blouse in an all-over LV Monogram floral print with a tie-neck and ruffle cuffs.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Embossed Cotton Tee','Louis Vuitton','UNISEX','Cotton Jersey','LV SS 2026','Clean-cut cotton jersey tee with a tone-on-tone LV monogram emboss across the chest.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Chain-Print Silk Top','Louis Vuitton','WOMEN','Silk Twill','LV FW 2026','Silk twill blouse in an LV chain-link print with a pussy-bow neck tie and long sleeves.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Damier Knit Top','Louis Vuitton','WOMEN','Damier Knit','LV FW 2026','Fitted sleeveless knit top in a Damier-check jacquard pattern with a ribbed hem.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Tops & Silk Blouses' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Flower Embroidered Blouse','Louis Vuitton','WOMEN','Cotton Poplin','LV SS 2026','White cotton poplin blouse with the LV floral embroidery at the collar and cuffs.','ACTIVE',NULL,NOW(),NOW());

-- OUTERWEAR & TAILORED JACKETS (5 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Denim Jacket','Louis Vuitton','UNISEX','LV Monogram Denim','LV SS 2026','Classic trucker-style jacket in LV-logo denim with tonal stitching and brass hardware.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Emprise Embossed Leather Jacket','Louis Vuitton','WOMEN','LV-Embossed Leather','LV FW 2026','Structured leather jacket with an all-over embossed LV motif and a zip-front closure.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Double-Faced Wool Coat','Louis Vuitton','WOMEN','Double-Face Wool','LV FW 2026','Belted longline coat in double-faced wool with an LV-engraved button front.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Windbreaker Monogram','Louis Vuitton','UNISEX','Nylon Taffeta','LV SS 2026','Packable monogram nylon taffeta windbreaker with a hidden hood and LV logo zipper pulls.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Outerwear & Tailored Jackets' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Tailored Wool Blazer','Louis Vuitton','MEN','Italian Wool','LV FW 2026','Sharp single-breasted blazer in Italian wool with a notch lapel and LV logo buttons.','ACTIVE',NULL,NOW(),NOW());

-- FOOTWEAR & LEATHER SHOES (7 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Archlight Sneakers','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','The Archlight sneaker with a futurist curved sole in Monogram canvas and leather trims.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Trainer Sneakers','Louis Vuitton','UNISEX','Monogram Denim','LV SS 2026','Oversized LV Trainer in Monogram denim with a translucent rubber cupsole.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Madeleine Pump','Louis Vuitton','WOMEN','Smooth Calfskin','LV FW 2026','Pointed-toe stiletto pump in smooth calfskin with the LV metal monogram plaque at the heel.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Flat Sandals','Louis Vuitton','WOMEN','Monogram Canvas','LV SS 2026','Thong flat sandals in Monogram canvas with a leather footbed and gold-tone LV hardware.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Pilot Ankle Boots','Louis Vuitton','WOMEN','Monogram Canvas','LV FW 2026','Chunky platform ankle boots in Monogram canvas with a zip-front and a lug outsole.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Men''s Manhattan Loafers','Louis Vuitton','MEN','Damier Graphite Canvas','LV FW 2026','Men''s slip-on loafers in Damier Graphite canvas with a leather lining and stacked heel.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Footwear & Leather Shoes' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Moccasins','Louis Vuitton','UNISEX','Monogram Canvas','LV SS 2026','Slip-on moccasins in Monogram canvas with a hand-sewn apron toe and leather sole.','ACTIVE',NULL,NOW(),NOW());

-- MONOGRAM SILK ACCESSORIES (5 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Square Scarf 90','Louis Vuitton','UNISEX','Silk Twill','LV SS 2026','90x90cm pure silk twill scarf in the iconic LV Monogram pattern with hand-rolled edges.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Initiales 40mm Belt','Louis Vuitton','UNISEX','Monogram Canvas','LV SS 2026','Classic 40mm reversible belt in Monogram canvas with polished LV Initiales buckle.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Cashmere Shawl','Louis Vuitton','UNISEX','Cashmere','LV FW 2026','Oversized cashmere shawl woven with the LV Monogram motif and finished with fringe trim.','ACTIVE','LIMITED_EDITION',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Zippy Coin Purse','Louis Vuitton','UNISEX','Monogram Canvas','LV SS 2026','Compact Zippy coin purse in Monogram canvas with a gold-tone zipper and card slots.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Monogram Silk Accessories' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Bandeau','Louis Vuitton','WOMEN','Silk Twill','LV SS 2026','Slim 6x100cm silk twill bandeau in the LV Monogram print — wear as hair tie or wrist wrap.','ACTIVE','NEW_ARRIVAL',NOW(),NOW());

-- MEN'S DESIGNER COLLECTION (7 products)
INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Hoodie','Louis Vuitton','MEN','French Terry Cotton','LV FW 2026','Heavyweight French terry hoodie with an all-over embossed LV Monogram print.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Damier Classic Polo','Louis Vuitton','MEN','Pique Cotton','LV SS 2026','Three-button pique polo shirt with a Damier-check collar and cuff trim.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Crest Chino Pants','Louis Vuitton','MEN','Stretch Cotton Chino','LV SS 2026','Slim-fit chino trousers with the embroidered LV crest at the pocket and a clean finish.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Monogram Tracksuit Jacket','Louis Vuitton','MEN','Technical Jersey','LV FW 2026','Zip-front tracksuit jacket in technical jersey with an all-over tonal Monogram print.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton LV Signature Short-Sleeve Shirt','Louis Vuitton','MEN','Cotton Poplin','LV SS 2026','Relaxed poplin short-sleeve shirt with the LV Signature all-over print and a camp collar.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Damier Graphite Wallet','Louis Vuitton','MEN','Damier Graphite Canvas','LV FW 2026','Slim bifold wallet in Damier Graphite canvas with six card slots and a note compartment.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'louis-vuitton' LIMIT 1),'PHYSICAL_APPAREL','Louis Vuitton Virgil Abloh Graphic Tee','Louis Vuitton','MEN','Supima Cotton','LV SS 2026','Archive Virgil Abloh-era graphic tee in Supima cotton with a bold LV runway print.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'Louis Vuitton';
