-- ============================================================
-- PART 1 of 4 — Ralph Lauren RLX (Men's Designer Collection)
-- 25 products | Run in Neon Query Editor
-- Prerequisite: brands row with slug='ralph-lauren-rlx' exists
-- ============================================================

INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, material_fabric, season_collection, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Performance Polo','Ralph Lauren RLX','MEN','Moisture-Wicking Pique','Spring/Summer 2026','Tech-performance polo in moisture-wicking pique with UV protection and 4-way stretch fit.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Stretch Oxford Shirt','Ralph Lauren RLX','MEN','Stretch Oxford Cotton','Spring/Summer 2026','Classic Oxford shirt in a 2-way stretch cotton blend with a point collar and chest pocket.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Linen Casual Shirt','Ralph Lauren RLX','MEN','Enzyme-Washed Linen','Spring/Summer 2026','Enzyme-washed linen shirt with a camp collar and coconut shell buttons.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Classic Chino Pants','Ralph Lauren RLX','MEN','Stretch Cotton Chino','Spring/Summer 2026','Slim-fit chino trousers in stretch cotton with a flat front and side pockets.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Tech Fleece Hoodie','Ralph Lauren RLX','MEN','Tech Fleece','Fall/Winter 2026','Midweight tech fleece pullover hoodie with ergonomic seams and a kangaroo pocket.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Merino Crewneck','Ralph Lauren RLX','MEN','Merino Wool','Fall/Winter 2026','Slim merino wool crewneck sweater with ribbed trims — a wardrobe essential.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Stretch Swim Shorts','Ralph Lauren RLX','MEN','Recycled Polyester','Spring/Summer 2026','Quick-dry swim shorts in recycled polyester with a drawstring waist and mesh brief.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Wool Blazer','Ralph Lauren RLX','MEN','Italian Wool','Fall/Winter 2026','Two-button Italian wool blazer with a notch lapel and flap pockets.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Quilted Down Vest','Ralph Lauren RLX','MEN','Down-Fill Nylon','Fall/Winter 2026','Lightweight quilted down vest with a stand collar and zip pockets.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Active Track Pants','Ralph Lauren RLX','MEN','Performance Jersey','Spring/Summer 2026','Slim track pants in performance jersey with a side stripe and zip ankle cuffs.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Graphic Print Tee','Ralph Lauren RLX','MEN','Supima Cotton','Spring/Summer 2026','Relaxed-fit graphic tee in Supima cotton with a vintage RLX logo print at the chest.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Knit Polo Shirt','Ralph Lauren RLX','MEN','Cotton Pique Knit','Spring/Summer 2026','Italian cotton pique polo with the embroidered polo player logo on the chest.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Selvedge Denim Jeans','Ralph Lauren RLX','MEN','Selvedge Denim','Fall/Winter 2026','Slim-straight Japanese selvedge denim jeans in a classic indigo wash.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Sea Island Cotton Shirt','Ralph Lauren RLX','MEN','Sea Island Cotton','Fall/Winter 2026','Non-iron spread-collar dress shirt in 100% Sea Island cotton — formally perfect.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Cashmere Scarf','Ralph Lauren RLX','MEN','Pure Cashmere','Fall/Winter 2026','Men''s 200x35cm cashmere scarf with fringed ends and an embroidered pony logo.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Packable Windbreaker','Ralph Lauren RLX','MEN','Ripstop Nylon','Spring/Summer 2026','Packable ripstop nylon windbreaker with a hidden hood and reflective logo trim.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Plush Terry Robe','Ralph Lauren RLX','MEN','Plush Terry Cotton','Fall/Winter 2026','Heavyweight plush terry cotton robe with embroidered RLX monogram on the chest.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX 5-Panel Performance Cap','Ralph Lauren RLX','MEN','Tech Canvas','Spring/Summer 2026','Water-resistant tech canvas 5-panel cap with an adjustable strap back.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Garment-Dyed Cargo Shorts','Ralph Lauren RLX','MEN','Garment-Dyed Cotton','Spring/Summer 2026','Garment-dyed cargo shorts with multiple pockets and a drawstring waist.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Full-Zip Active Jacket','Ralph Lauren RLX','MEN','Stretch Tech Fabric','Spring/Summer 2026','Full-zip performance jacket in 4-way stretch tech fabric with ventilation panels.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Luxe Oxford Blazer','Ralph Lauren RLX','MEN','Stretch Oxford Cotton','Fall/Winter 2026','Unstructured oxford blazer with stretch — goes from office to weekend with ease.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Fleece Quarter-Zip','Ralph Lauren RLX','MEN','Tech Fleece','Fall/Winter 2026','Quarter-zip fleece pullover in brushed tech fabric with reflective RLX detailing.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Performance Training Shorts','Ralph Lauren RLX','MEN','4-Way Stretch Nylon','Spring/Summer 2026','7-inch inseam training shorts in 4-way stretch nylon with liner and zip pockets.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX Tech Jogger Pants','Ralph Lauren RLX','MEN','Stretch Nylon Twill','Fall/Winter 2026','Slim-fit nylon twill jogger pants with articulated knees and zip ankle cuffs.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Men''s Designer Collection' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'ralph-lauren-rlx' LIMIT 1),'PHYSICAL_APPAREL','Ralph Lauren RLX UV Tennis Tee','Ralph Lauren RLX','MEN','UV-Block Pique','Spring/Summer 2026','Moisture-wicking UV-protective pique tennis tee with embroidered polo player logo.','ACTIVE',NULL,NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'Ralph Lauren RLX';
