-- ============================================================
-- PART 4 of 4 — KWD Publishing House
-- 15 products: Digital eBooks & Publications
-- Run in Neon Query Editor
-- Prerequisite: brands row with slug='kwd-publishing' exists
-- ============================================================

INSERT INTO products (category_id, brand_id, product_type, product_name, brand, gender, season_collection, author_artist, isbn_code, description, status, featured_badge, created_at, updated_at) VALUES
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','The Phnom Penh Style Guide 2026','KWD Publishing House','UNISEX','KWD Catalogue 2026','Sopheaktra Keo','978-99963-00-001-1','The definitive editorial guide to contemporary Cambodian fashion, art, and urban lifestyle.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Retail Management for Southeast Asia','KWD Publishing House','UNISEX','KWD Catalogue 2026','Dr. Chantrea Lim','978-99963-00-002-8','Comprehensive retail operations handbook covering inventory, POS, and omnichannel strategy.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Laravel Backend Architecture 2026','KWD Publishing House','UNISEX','KWD Catalogue 2026','Kesara Ram','978-99963-00-003-5','Full-stack Laravel API architecture guide with PostgreSQL, Redis, and cloud deployment.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Khmer Textile Heritage Handbook','KWD Publishing House','UNISEX','KWD Catalogue 2026','Prof. Borey Chan','978-99963-00-004-2','An illustrated study of traditional Cambodian silk weaving, textile patterns, and cultural significance.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Visual Branding Masterclass','KWD Publishing House','UNISEX','KWD Catalogue 2026','Nary Phon','978-99963-00-005-9','From logo design to brand identity systems — a practical visual branding course in ebook form.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','React & Next.js Full Stack Development','KWD Publishing House','UNISEX','KWD Catalogue 2026','Kosal Pich','978-99963-00-006-6','Modern React 18 and Next.js 14 development guide with TypeScript and Tailwind CSS.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Southeast Asia Investment Guide 2026','KWD Publishing House','UNISEX','KWD Catalogue 2026','Vuth Sovann','978-99963-00-007-3','Market entry and investment strategy guide covering Cambodia, Vietnam, and Thailand.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Luxury Brand Marketing Strategies','KWD Publishing House','UNISEX','KWD Catalogue 2026','Chenda Mak','978-99963-00-008-0','How luxury fashion houses build aspiration, exclusivity, and global brand equity.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Cloud & DevOps Engineering Handbook','KWD Publishing House','UNISEX','KWD Catalogue 2026','Piseth Heng','978-99963-00-009-7','AWS, Docker, Kubernetes, and CI/CD pipeline engineering for production-grade applications.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Cambodian Cuisine: The Modern Cookbook','KWD Publishing House','UNISEX','KWD Catalogue 2026','Makara Sok','978-99963-00-010-3','Contemporary interpretations of Khmer cuisine with 80 recipes and culinary photography.','ACTIVE','BEST_SELLER',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','PostgreSQL Performance Tuning Guide','KWD Publishing House','UNISEX','KWD Catalogue 2026','Dara Nhem','978-99963-00-011-0','Advanced PostgreSQL indexing, query optimisation, and scaling strategies for high-load apps.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Phnom Penh Architecture & Urbanism','KWD Publishing House','UNISEX','KWD Catalogue 2026','Vannak Ros','978-99963-00-012-7','An illustrated history of Cambodian architecture from the Khmer Empire to contemporary design.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Digital Marketing in Emerging Markets','KWD Publishing House','UNISEX','KWD Catalogue 2026','Sokunthea Oum','978-99963-00-013-4','Social media, SEO, and performance marketing strategies tailored to Southeast Asian markets.','ACTIVE','NEW_ARRIVAL',NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','Sustainable Fashion & Slow Style','KWD Publishing House','UNISEX','KWD Catalogue 2026','Lyda Sorn','978-99963-00-014-1','A guide to building a conscious wardrobe, ethical fashion consumption, and sustainable styling.','ACTIVE',NULL,NOW(),NOW()),
((SELECT category_id FROM categories WHERE category_name = 'Digital eBooks & Publications' LIMIT 1),(SELECT brand_id FROM brands WHERE slug = 'kwd-publishing' LIMIT 1),'DIGITAL_DOWNLOAD','KWD Complete Business Library Bundle','KWD Publishing House','UNISEX','KWD Catalogue 2026','KWD Editorial Team','978-99963-00-015-8','All 14 KWD titles in one discounted enterprise bundle — unlimited team access PDF license.','ACTIVE','LIMITED_EDITION',NOW(),NOW());

-- verify: SELECT COUNT(*) FROM products WHERE brand = 'KWD Publishing House';
